version: "3"
services:
    api:
        image: snadim92/fastapi:latest
        ports:
            - 8080:8000    
        depends_on:
            - db
        environment:
            - database_hostname=${DATABASE_HOSTNAME}
            - database_port=${DATABASE_PORT}
            - database_name=${DATABASE_NAME}
            - database_username=${DATABASE_USERNAME}
            - database_password=${DATABASE_PASSWORD}
            - secret_key=${DATABASE_SECRET}
            - algorithm=${DATABASE_ALGORITHM}
            - access_token_expire_minutes=${DATABASE_TOKEN_EXPIRE_MINUTES}

    db:
        image: postgres:latest
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
    db_data: