version: "3"
services:
    api:
        build: .
        ports:
            - 8080:8000    
        depends_on:
            - db
        environment:
            - database_hostname=${database_hostname}
            - database_port=${database_port}
            - database_name=${database_name}
            - database_username=${database_username}
            - database_password=${database_password}
            - secret_key=${database_secret}
            - algorithm=${database_algorithm}
            - access_token_expire_minutes=${database_token_expire_minutes}

    db:
        image: postgres:latest
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${database_name}
            - POSTGRES_USER=${database_username}
            - POSTGRES_PASSWORD=${database_password}

volumes:
    db_data: